renewable_dbt:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('WAGA_SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('WAGA_SNOWFLAKE_USER') }}"
      private_key_path: "{{ env_var('WAGA_SNOWFLAKE_PRIVATE_KEY_PATH', '') }}"
      role: "{{ env_var('WAGA_SNOWFLAKE_ROLE') }}"
      warehouse: "{{ env_var('WAGA_SNOWFLAKE_WAREHOUSE') }}"
      database: "{{ env_var('WAGA_SNOWFLAKE_DATABASE', 'WAGA') }}"
      schema: STAGING
      threads: 4
